### ISSUE TITLE
Uniqueness field mismatches

### ISSUE THREAD

**Issue by TheBuzzSaw** [swccgpc/swccg-card-json#148]
Given that the titles of each card contain their uniqueness, do we even care about the `"uniqueness"` field anymore? If we do, we have quite a few mismatches that need addressing. Otherwise, I'd say let's purge that field.

    Card front •A Brave Resistance mismatch with uniqueness ().
    Card front •Aayla Secura (AI) mismatch with uniqueness ().
    Card front •Admiral Raddus mismatch with uniqueness ().
    Card front •Ahch-To mismatch with uniqueness ().
    Card front •Ahch-To: Cliffs mismatch with uniqueness ().
    Card front •Ahch-To: Jedi Temple mismatch with uniqueness ().
    Card front •Ahch-To: Jedi Village mismatch with uniqueness ().
    Card front •Ahch-To: Luke's Hut mismatch with uniqueness ().
    Card front •Ahch-To: Saddle mismatch with uniqueness ().
    Card front •Ahsoka Tano mismatch with uniqueness ().
    Card front •Ambush (V) mismatch with uniqueness ().
    Card front •Anakin Skywalker, Padawan Learner (AI) mismatch with uniqueness ().
    Card front •Anakin's Lightsaber (V) mismatch with uniqueness ().
    Card front •Ancient Watering Hole mismatch with uniqueness ().
    Card front •Are You Okay? mismatch with uniqueness ().
    Card front •Artoo, Brave Little Droid (AI) mismatch with uniqueness ().
    Card front •Azure Angel (AI) mismatch with uniqueness ().
    Card front •BB-8 In Black Squadron 1 mismatch with uniqueness ().
    Card front •Beldon's Eye & •All My Urchins mismatch with uniqueness ().
    Card front •Blue 11 mismatch with uniqueness ().
    Card front •Blue Squadron 1 mismatch with uniqueness ().
    Card front •BoShek (V) mismatch with uniqueness ().
    Card front •Boss Nass (AI) mismatch with uniqueness ().
    Card front •Bravo Fighter (V) mismatch with uniqueness ().
    Card front •Chewie mismatch with uniqueness ().
    Card front •••Clone Squad Leader mismatch with uniqueness ().
    Card front •Cloning Cylinders mismatch with uniqueness ().
    Card front •Commander Ruescott Melshi mismatch with uniqueness ().
    Card front •Commander Vanden Willard (V) mismatch with uniqueness ().
    Card front •CT-5385 (Tup) mismatch with uniqueness ().
    Card front •Cyborg Construct (V) mismatch with uniqueness ().
    Card front •Dark Approach mismatch with uniqueness ().
    Card front •Dash Rendar (V) mismatch with uniqueness ().
    Card front •Don't Do That Again (Tatooine) (V) mismatch with uniqueness ().
    Card front •Dutch (V) mismatch with uniqueness ().
    Card front •Ellorrs Madak, Pilot Instructor mismatch with uniqueness ().
    Card front •I Don't Like Sand mismatch with uniqueness ().
    Card front •Eyes In The Dark mismatch with uniqueness ().
    Card front •Ezra Bridger mismatch with uniqueness ().
    Card front •Force Projection mismatch with uniqueness ().
    Card front •Galen Erso mismatch with uniqueness ().
    Card front •General Dodonna (V) mismatch with uniqueness ().
    Card front •General Jar Jar (AI) mismatch with uniqueness ().
    Card front •General Kenobi mismatch with uniqueness ().
    Card front •General Walex Blissex (V) mismatch with uniqueness ().
    Card front •Gift Of The Mentor mismatch with uniqueness ().
    Card front •Gold Leader In Gold 1 mismatch with uniqueness ().
    Card front •Graveyard Of Giants mismatch with uniqueness ().
    Card front •Hoth: Defensive Perimeter (3rd Marker) mismatch with uniqueness ().
    Card front •Hoth: Main Power Generators (1st Marker) mismatch with uniqueness ().
    Card front •Hoth: Main Power Generators (1st Marker) (V) mismatch with uniqueness ().
    Card front •Hoth: North Ridge (4th Marker) mismatch with uniqueness ().
    Card front •Hoth: Snow Trench (2nd Marker) mismatch with uniqueness ().
    Card front •I Think I Can Handle Myself mismatch with uniqueness ().
    Card front •I'm Getting Pretty Good At This mismatch with uniqueness ().
    Card front •It's Not My Fault! mismatch with uniqueness ().
    Card front •It's True, All Of It mismatch with uniqueness ().
    Card front •I've Got A Bad Feeling About ... mismatch with uniqueness ().
    Card front •Jabba's Prize/Jabba's Prize (V) mismatch with uniqueness ().
    Card back •Jabba's Prize/Jabba's Prize (V) mismatch with uniqueness ().
    Card front •Jedi Business mismatch with uniqueness ().
    Card front •Jedi Mind Trick (V) mismatch with uniqueness ().
    Card front •Kamino mismatch with uniqueness ().
    Card front •Kamino: Clone Birthing Center mismatch with uniqueness ().
    Card front •Kamino: Clone Training Center mismatch with uniqueness ().
    Card front •Kit Fisto mismatch with uniqueness ().
    Card front •Knights Of The Old Republic mismatch with uniqueness ().
    Card front •Lak Sivrak mismatch with uniqueness ().
    Card front •LE-BO2D9 (Leebo) mismatch with uniqueness ().
    Card front •Libertine mismatch with uniqueness ().
    Card front •Lieutenant Kaydel Connix mismatch with uniqueness ().
    Card front •Lightmaker mismatch with uniqueness ().
    Card front •Luke Skywalker, The Last Jedi mismatch with uniqueness ().
    Card front •Mace Windu (AI) mismatch with uniqueness ().
    Card front •Mace Windu (V) (AI) mismatch with uniqueness ().
    Card front •Mace Windu, Jedi Master (AI) mismatch with uniqueness ().
    Card front •Make Ten Men Feel Like A Hundred mismatch with uniqueness ().
    Card front •Master Qui-Gon (AI) mismatch with uniqueness ().
    Card front •Master Qui-Gon (V) (AI) mismatch with uniqueness ().
    Card front •Maz Kanata mismatch with uniqueness ().
    Card front •Maz's Castle: Antechamber mismatch with uniqueness ().
    Card front •Maz's Castle: Hidden Recess mismatch with uniqueness ().
    Card front ••Mon Calamari Admiral mismatch with uniqueness (***).
    Card front •Nar Shaddaa Wind Chimes & •Out Of Somewhere mismatch with uniqueness ().
    Card front •Obi-Wan Kenobi, Padawan Learner (AI) mismatch with uniqueness ().
    Card front •Obi-Wan Kenobi, Padawan Learner (V) (AI) mismatch with uniqueness ().
    Card front •Odin Nesloor & •First Aid mismatch with uniqueness ().
    Card front •Padme Naberrie (AI) mismatch with uniqueness ().
    Card front •Padme Naberrie (V) (AI) mismatch with uniqueness ().
    Card front •Panaka, Protector Of The Queen (AI) mismatch with uniqueness ().
    Card front •Paploo (V) mismatch with uniqueness ().
    Card front •Part Of The Tribe mismatch with uniqueness ().
    Card front •Plo Koon (V) mismatch with uniqueness ().
    Card front •Queen Amidala (AI) mismatch with uniqueness ().
    Card front •Queen Amidala, Ruler Of Naboo (AI) mismatch with uniqueness ().
    Card front •Qui-Gon Jinn (AI) mismatch with uniqueness ().
    Card front •Qui-Gon Jinn's Lightsaber (AI) mismatch with uniqueness ().
    Card front •••Rebel Trooper Reinforcements mismatch with uniqueness ().
    Card front •Red 5 (V) mismatch with uniqueness ().
    Card front •Red Leader In Red 1 mismatch with uniqueness ().
    Card front •Relatively Unprotected mismatch with uniqueness ().
    Card front •Rescue In The Clouds (V) mismatch with uniqueness ().
    Card front •Rey (AI) mismatch with uniqueness ().
    Card front •Rey With Lightsaber mismatch with uniqueness ().
    Card front •Rose Tico mismatch with uniqueness ().
    Card front •••Sandcrawler: Loading Bay mismatch with uniqueness (*).
    Card front •Saw Gerrera mismatch with uniqueness ().
    Card front •Scarif mismatch with uniqueness ().
    Card front •Scarif: Beach mismatch with uniqueness ().
    Card front •Scarif: Data Vault mismatch with uniqueness ().
    Card front •Scarif: Landing Pad Nine (Docking Bay) mismatch with uniqueness ().
    Card front •Scarif: Turbolift Complex mismatch with uniqueness ().
    Card front •See You Around, Kid mismatch with uniqueness ().
    Card front •Senate Hovercam mismatch with uniqueness ().
    Card front •Senator Palpatine (AI) mismatch with uniqueness ().
    Card front •Squadron Assignments (V) mismatch with uniqueness ().
    Card front •Stardust mismatch with uniqueness ().
    Card front •Steady, Steady mismatch with uniqueness ().
    Card front •Stolen First Order TIE Fighter mismatch with uniqueness ().
    Card front •Supreme Chancellor Valorum (AI) mismatch with uniqueness ().
    Card front •Surreptitious Glance mismatch with uniqueness ().
    Card front •Taidu Sefla mismatch with uniqueness ().
    Card front •Takodana mismatch with uniqueness ().
    Card front •Takodana: Maz's Castle mismatch with uniqueness ().
    Card front •Tallie Lintra In Blue 1 mismatch with uniqueness ().
    Card front •The Falcon, Junkyard Garbage/•The Falcon, Junkyard Garbage mismatch with uniqueness ().
    Card back •The Falcon, Junkyard Garbage/•The Falcon, Junkyard Garbage mismatch with uniqueness ().
    Card front •The Garbage Will Do mismatch with uniqueness ().
    Card front •The Republic No Longer Functions mismatch with uniqueness ().
    Card front •There Is Another mismatch with uniqueness ().
    Card front •Threepio With His Parts Showing (AI) mismatch with uniqueness ().
    Card front •Vice Admiral Holdo mismatch with uniqueness ().
    Card front •WED-9-M1 'Bantha' Droid mismatch with uniqueness ().
    Card front •WHAAAAAAAAAOOOOW! mismatch with uniqueness ().
    Card front •Where's Han? mismatch with uniqueness ().
    Card front •Yavin 4 (V) mismatch with uniqueness ().
    Card front •Yavin 4: Massassi Ruins (V) mismatch with uniqueness ().
    Card front •Yoda, Senior Council Member (AI) mismatch with uniqueness ().
    Card front •Your Insight Serves You Well (Death Star II) (V) mismatch with uniqueness ().
    Card front •Yoxgit (V) mismatch with uniqueness ().
    Card front •I've Got A Really Good Feeling About This mismatch with uniqueness ().
    Card front •Savareen Standoff mismatch with uniqueness ().
    Card front •Death Star II: Chasm Walkway mismatch with uniqueness ().
    Card front •Puck mismatch with uniqueness ().
    Card front •Ahsoka's Shoto Lightsaber mismatch with uniqueness ().
    Card front •Uncivilized Blaster mismatch with uniqueness ().
    Card front •Agent Kallus (AI) mismatch with uniqueness ().
    Card front ••Always Two There Are mismatch with uniqueness ().
    Card front •Apology Accepted (V) mismatch with uniqueness ().
    Card front •Aurra Sing (AI) mismatch with uniqueness ().
    Card front •••B2 Battle Droid mismatch with uniqueness ().
    Card front •Bala-Tik mismatch with uniqueness ().
    Card front •Black 3 (V) mismatch with uniqueness ().
    Card front •Boba Fett (V) mismatch with uniqueness ().
    Card front •Carbonite Chamber Console (V) mismatch with uniqueness ().
    Card front •Chief Bast (V) mismatch with uniqueness ().
    Card front •Come Here You Big Coward mismatch with uniqueness ().
    Card front •Commander Brandei (V) mismatch with uniqueness ().
    Card front •Coruscant: 500 Republica mismatch with uniqueness ().
    Card front •Coruscant: Private Platform (Docking Bay) mismatch with uniqueness ().
    Card front •Counter Surprise Assault mismatch with uniqueness ().
    Card front •Darth Maul (AI) mismatch with uniqueness ().
    Card front •Darth Maul, Young Apprentice (AI) mismatch with uniqueness ().
    Card front •Darth Sidious (AI) mismatch with uniqueness ().
    Card front •Death Squadron Assignment mismatch with uniqueness ().
    Card front •Death Star Reactor Terminal mismatch with uniqueness ().
    Card front •••Death Trooper (V) mismatch with uniqueness ().
    Card front •Dianoga mismatch with uniqueness ().
    Card front •Don't Move! mismatch with uniqueness ().
    Card front •Dr. Chelli Lona Aphra mismatch with uniqueness ().
    Card front •Fanfare (Tatooine) (V) mismatch with uniqueness ().
    Card front •••First Order Special Forces TIE mismatch with uniqueness ().
    Card front •General Grievous mismatch with uniqueness ().
    Card front •General Grievous (AI) mismatch with uniqueness ().
    Card front •General Grievous (OAI) mismatch with uniqueness ().
    Card front •Hondo Ohnaka mismatch with uniqueness ().
    Card front •Hoth: Defensive Perimeter (3rd Marker) mismatch with uniqueness ().
    Card front •Hoth: Ice Plains (5th Marker) mismatch with uniqueness ().
    Card front •Hoth: Ice Plains (5th Marker) (V) mismatch with uniqueness ().
    Card front •Hoth: Mountains (6th Marker) mismatch with uniqueness ().
    Card front •Hoth: North Ridge (4th Marker) mismatch with uniqueness ().
    Card front •Hoth: Wampa Cave (7th Marker) mismatch with uniqueness ().
    Card front •I Find Your Lack Of Faith Disturbing (V) mismatch with uniqueness ().
    Card front •I Never Ask That Question mismatch with uniqueness ().
    Card front •••IG MagnaGuard mismatch with uniqueness ().
    Card front •Imperial Artillery mismatch with uniqueness (**).
    Card front •Imperial Detention (V) mismatch with uniqueness ().
    Card front •Coarse And Rough And Irritating mismatch with uniqueness ().
    Card front •Invisible Hand mismatch with uniqueness ().
    Card front •Invisible Hand: Bridge mismatch with uniqueness ().
    Card front •Invisible Hand: Docking Bay mismatch with uniqueness ().
    Card front •Invisible Hand: Hallway 328 mismatch with uniqueness ().
    Card front •Invisible Hand: Observatory Entrance mismatch with uniqueness ().
    Card front •Jabba's Prize/Jabba's Prize mismatch with uniqueness ().
    Card back •Jabba's Prize/Jabba's Prize mismatch with uniqueness ().
    Card front •Jabba's Space Cruiser (V) mismatch with uniqueness ().
    Card front •Jedha: Jedha City mismatch with uniqueness ().
    Card front •Krennic, Death Star Commandant mismatch with uniqueness ().
    Card front •Kylo Ren With Lightsaber mismatch with uniqueness ().
    Card front •Kylo Ren's TIE Silencer mismatch with uniqueness ().
    Card front •Lady Proxima mismatch with uniqueness ().
    Card front •Lana Dobreed & •Sacrifice mismatch with uniqueness ().
    Card front •Lieutenant Venka (V) mismatch with uniqueness ().
    Card front •Lobel mismatch with uniqueness ().
    Card front •Lt. Poldin Lehuse mismatch with uniqueness ().
    Card front •Luke Skywalker, The Emperor's Prize/Luke Skywalker, The Emperor's Prize mismatch with uniqueness ().
    Card back •Luke Skywalker, The Emperor's Prize/Luke Skywalker, The Emperor's Prize mismatch with uniqueness ().
    Card front •Marquand In Blizzard 6 mismatch with uniqueness ().
    Card front •Maul's Sith Infiltrator (AI) mismatch with uniqueness ().
    Card front •Mitth'raw'nuruodo mismatch with uniqueness ().
    Card front •Mustafar mismatch with uniqueness ().
    Card front •Mustafar: Vader's Castle mismatch with uniqueness ().
    Card front •Myn Kyneugh (V) mismatch with uniqueness ().
    Card front •Nute Gunray (V) mismatch with uniqueness ().
    Card front •Nute Gunray, Neimoidian Viceroy (AI) mismatch with uniqueness ().
    Card front •Ponda Baba's Hold-out Blaster mismatch with uniqueness ().
    Card front •Precision Targeting mismatch with uniqueness ().
    Card front •Prepare For A Surface Attack (V) mismatch with uniqueness ().
    Card front •Pride Of The Empire (V) mismatch with uniqueness ().
    Card front •Quietly Observing (V) mismatch with uniqueness ().
    Card front •Ree-Yees (V) mismatch with uniqueness ().
    Card front •Rolling, Rolling, Rolling mismatch with uniqueness ().
    Card front •Rune Haako, Legal Counsel (AI) mismatch with uniqueness ().
    Card front •••Sandcrawler: Droid Junkheap mismatch with uniqueness (*).
    Card front •Sebulba (AI) mismatch with uniqueness ().
    Card front •Sebulba (V) mismatch with uniqueness ().
    Card front •Sebulba (V) (AI) mismatch with uniqueness ().
    Card front •Sergeant Narthax With E-web Blaster mismatch with uniqueness ().
    Card front •Shadows Of The Empire mismatch with uniqueness ().
    Card front •Short-range Fighters mismatch with uniqueness ().
    Card front •Slave I, Symbol Of Fear (AI) mismatch with uniqueness ().
    Card front •Supreme Leader Snoke mismatch with uniqueness ().
    Card front •The Grand Inquisitor mismatch with uniqueness ().
    Card front •The Phantom Menace (AI) mismatch with uniqueness ().
    Card front •They Will Be No Match For You (V) mismatch with uniqueness ().
    Card front •Trade Federation Tactics (V) mismatch with uniqueness ().
    Card front •Twi'lek Advisor (V) mismatch with uniqueness ().
    Card front •URoRRuR'R'R's Bantha mismatch with uniqueness ().
    Card front •Vader's Anger (V) mismatch with uniqueness ().
    Card front •Vanee mismatch with uniqueness ().
    Card front •Veers mismatch with uniqueness ().
    Card front •Vengeance (V) mismatch with uniqueness ().
    Card front •Watto (AI) mismatch with uniqueness ().
    Card front •Weapon Malfunction mismatch with uniqueness ().
    Card front •Wittin's Sandcrawler mismatch with uniqueness ().
    Card front •Xizor's Palace: Sewer mismatch with uniqueness ().
    Card front •You Cannot Hide Forever (Death Star II) (V) mismatch with uniqueness ().
    Card front •Admiral Trench mismatch with uniqueness ().
    Card front •Allegiant General Pryde mismatch with uniqueness ().
    Card front •Aurra Sing With Blaster Rifle mismatch with uniqueness ().
    Card front •Aurra Sing With Blaster Rifle (AI) mismatch with uniqueness ().
    Card front •Moff Gideon mismatch with uniqueness ().
    Card front •Insignificant Rebellion (V) mismatch with uniqueness ().
    Card front •Dathomir: Maul's Chambers mismatch with uniqueness ().
    Card front •First Light: Bar mismatch with uniqueness ().
    Card front •First Light: Dryden's Study mismatch with uniqueness ().
    Card front •First Light: Reception Area mismatch with uniqueness ().
    Card front •Malachor: Sith Temple Upper Chamber mismatch with uniqueness ().
    Card front •Malachor: Sith Temple Entrance mismatch with uniqueness ().
    Card front •Captain Khurgee (V) mismatch with uniqueness ().
    Card front •Darksaber mismatch with uniqueness ().
    Card front •Blizzard 8 mismatch with uniqueness ().
    Card front ••Rise Of The Sith mismatch with uniqueness (*).

**Comment by DevoKun** [comment]
There are several systems that allow you to search by uniqueness. We should maintain the field.

**Comment by scottrick** [comment]
I can fix this if you already aren't tackling this.  I have a script I can do this pretty easily with.

**Comment by TheBuzzSaw** [comment]
@scottrick I only planned to tackle it if #151 is addressed first. You're fine to proceed if you're already working on it.
