### ISSUE TITLE
JSON Schema

### ISSUE THREAD

**Issue by TheBuzzSaw** [swccgpc/swccg-card-json#150]
I noticed that the properties throughout the JSON are not in a consistent order. This is generally fine as it is a human-drive process, but it complicates efforts to automate data transformations. For instance, I could fix all of #148 in a second with my tooling, but it would trigger a massive diff due to all the properties being rearranged.

Maybe we just rip the band-aid off and have one PR that standardizes the property ordering. We could either add a file detailing the official order of properties, or we just settle on a rule of alphabetizing all properties.

Thoughts?

**Comment by DevoKun** [comment]
Unlike a list, keys are the primary entry point to a value. The order of keys is not important within a map.

**Comment by scottrick** [comment]
Not sure how you are outputting the JSON, but if you follow the ordering here:

https://github.com/scottrick/swccg-json-parser/tree/main/src/main/kotlin/com/hatfat/swccg/json/parse/data

I think it should be mostly correct.

**Comment by TheBuzzSaw** [comment]
@scottrick I figured just switching to raw alphabetization would be the most future-proof solution and no one would ever need to lookup the order of fields.

**Comment by scottrick** [comment]
Yeah that might be better.  I did it in this order because it minimized the diff while giving everything the same order.
