### ISSUE TITLE
Your Ship? (V)

### ISSUE THREAD

**Issue by scottrick** [swccgpc/swccg-card-json#3]
"Your Ship? (V)" also has an incorrect imageUrl, but I'm not sure what its supposed to be.  I don't see it in the holotable github repo so I'm not sure what to change it to.

**Comment by thomasmarlin** [comment]
Just pushed a fix for this.  Path was: "https://res.starwarsccg.org/cards/Images-HT/starwars/VirtualPremium-Light/large/yourship.gif?raw=true"
