### ISSUE TITLE
First/Second Anthology Cards

### ISSUE THREAD

**Issue by scottrick** [swccgpc/swccg-card-json#50]
In order to properly handle the legality of cards in the first/second anthologies, I think we have two options:
1. Add another copy of the card to the json, marked with the anthology set.  
 - This is what gemp currently does.  The downside is that this card shows up twice in applicable searches and it means we have two places to update if these cards ever change.
2. Update the "set" field on each card to instead be "sets".  This field will contain a list of Strings, each describing a set the card belongs to.
 - This is a larger change to how the data is structured, but I feel this is the most accurate.
 - If the PC ever goes down the road of having card blocks that rotate in and out, I think this method will be preferred.  Each card could belong to multiple sets, the legality of which will change depending on the format you are considering.

**Comment by thomasmarlin** [comment]
I'd prefer to stick with #1 for now.  We have so few cards which fit into this category that I think simplicity is preferable. If the PC does go down the route of rotation, I think we'll have other issues, like having cards rotate in/out with subtly different changes as they cycle.  If you have a strong preference though, let me know and I can give it some further thought.

**Comment by thomasmarlin** [comment]
I know we talked about this the other day and decided that we'd go with:
1) Change "set": "string ->  "sets": [string]
2) Reference the "sets.json" file to determine the sets based on Id.

I just realized that we have a similar issue for all of our AIs.  For each of those AIs, we also have the exact same gametext as the original card.   We have AIs for the normal sets and we also have tons of AIs for virtual cards as well.

I also now realize that the rarity on the Anthology Preview cards will also be different.  In the Anthologies, the rarity would be "Premium", but the version in the regular sets would be "Rare".  Any thoughts on getting around that without duplicating the entire card entry?

This is making me rethink our previous decision and go back to duplicating

**Comment by EchoBaseTrooper** [comment]
When we talked about updating the JSON structure a few years ago I had suggested something like this:

"set": "main set it was printed/virtualized in [not necessarily first set it was printed in, list anthology as a printing instead of as the set]",
"rarity": "for virtual cards just put V or something",
"printings": [	
	{"set": "set1","border": "BB","foil":false,"misprint":false,"language":"English","alternateimage":false,"oversized":false,"reprint":false,"notes":"any relevant notes, for misprints describe what is misprinted"},	
	{"set": "set1","border": "WB","foil":false,"misprint":false,"language":"English","alternateimage":false,"oversized":false,"reprint":false,"notes":"any relevant notes, for misprints describe what is misprinted"}	
	],


Anthology/AI/foil versions would be in printings instead of entirely separate entries

**Comment by thomasmarlin** [comment]
> When we talked about updating the JSON structure a few years ago I had suggested something like this:
> 
> "set": "main set it was printed/virtualized in [not necessarily first set it was printed in, list anthology as a printing instead of as the set]",
> "rarity": "for virtual cards just put V or something",
> "printings": [
> {"set": "set1","border": "BB","foil":false,"misprint":false,"language":"English","alternateimage":false,"oversized":false,"reprint":false,"notes":"any relevant notes, for misprints describe what is misprinted"},
> {"set": "set1","border": "WB","foil":false,"misprint":false,"language":"English","alternateimage":false,"oversized":false,"reprint":false,"notes":"any relevant notes, for misprints describe what is misprinted"}
> ],
> 
> Anthology/AI/foil versions would be in printings instead of entirely separate entries

Something like that could work.  I think that does address all of the issues mentioned if we include the "rarity" and "imageUrl" inside that special "printings" array (so we can display the AIs somewhere).  It would also give us the flexibility to have links to Japanese cards, WB/BB as well, which would be interesting (though a large undertaking). 

Functionally, I do think it would would, but it feels a bit 'heavy'.  For the purposes of Scomp Link / card searching, I would want to not have the WB/BB/Japanese/Foil in every one of the cards. It just adds a ton to the file sizes without a much benefit. However from a "collector" perspective, I definitely *would* want it.  I wonder if there is some middle ground we can have.

**Comment by scottrick** [comment]
I really like the idea of having a "printings" field, but I think it should be distinct from the "sets" field.

When I think "sets", I think "legality".  When I think "printings", I think "white border", "black border", "foil", "AI", "misprint", "eratta'd", "japanese", etc.

In Premiere - Special Edition format, the Second Anthology cards are legal, and that data is contained in the "sets" field.  If a card is legal, you can use any of the printings.

So, I actually still think changing "set" to "sets" is the way to go.  Then in the future after we solidify on the definition of the "printings" field, we can remove the duplicate AI entries.  This is also when we can fix the rarity issue by removing rarity from the base card data and adding it to each printing.  I think we should leave rarity as is for now and it will just be incorrect for the Anthology cards.

**Comment by scottrick** [comment]
I opened a PR changing set -> sets.  This also includes handling the anthology cards correctly.  If anybody still has concerns with this change please speak up and I'm happy to discuss it further.

**Comment by EchoBaseTrooper** [comment]
What will you do for something like Naboo Occupation that was printed in Theed Palace but was first printed as a foil in Reflections III? Would you include Reflections III in sets?

**Comment by scottrick** [comment]
Good catch, I wasn't aware of that case, but if it was important for us to properly handle the Premiere - Ref3 format, then I think we would want to make sure all cards printed in Reflections III included Ref3 in their sets entry.  Do you know if there are other cards like that?

Because I really doubt that the Premiere - Ref3 format will ever be a thing, I think we would likely just ignore this scenario for now.  When the "printings" are added, it would have the appropriate Ref3 entry.

The other option would be to keep the "set" field and make that be the "primary set" in which the card appeared.  For the Anthology cards that would be SE/EDR/DS2 and for Naboo Occupation it would be Theed Palace.  Might be worth renaming set -> primarySet/mainSet if we think that's important.

**Comment by EchoBaseTrooper** [comment]
Yeah I only learned that about Naboo Occupation this week. There could easily be more I'm not aware of.

I do think we should have the "set" field be the primary set for a card and any other sets would be found in individual printings entries. I don't think we need to rename it as primarySet or anything, but if you do I think that would be fine.

**Comment by scottrick** [comment]
OK, I'm coming around to keeping the "set" field as the primary set.  

However, I don't feel like we are at a point right now where we need or are ready to create the full featured "printings" field.  What if we do this: 
- Keep the "set" field as is.
- Create the "printings" field but for now, have it contain only the list of set ids.  Basically rename "sets" to "printings".  In the future when we decide to flesh out what exactly a "printing" is, we can update the json with the new format.

**Comment by EchoBaseTrooper** [comment]
But then what are we doing with AIs now?

**Comment by scottrick** [comment]
OK, a new PR is up.  Instead of "sets", we have "printings" where each printing contains a set id.  This doesn't handle AIs currently but the framework is in place where we should be able to in the future.
