### ISSUE TITLE
[Light Side] icon vs [Light Side Force] icon?

### ISSUE THREAD

**Issue by ronhowe** [swccgpc/swccg-card-json#59]
There is inconsistency between how gametext references a force icon.

e.g.

![image](https://user-images.githubusercontent.com/5210043/109391725-93a7f000-78e6-11eb-8bdc-47808d99c962.png)

In some cases, a card will say [Light Side Force] icon(s) and in other cases it will say [Light Side] icon(s).

Which should we standardize on and would we want those also applied to legacy cards?

**Comment by scottrick** [comment]
I think [Light Side Force] makes more sense, and I like the idea of standardizing it.

**Comment by EchoBaseTrooper** [comment]
Any official text that is spelled out instead of using the image will use [Light Side] because that's what the proofing team uses. The AR has two examples that are both [Light Side].

**Comment by scottrick** [comment]
[Light Side] it is!

**Comment by ronhowe** [comment]
Would you want that applied to legacy cards too?

**Comment by EchoBaseTrooper** [comment]
I think so. It makes sense to standardize it.

**Comment by ronhowe** [comment]
(I hate the legacy cards.  Wish they could be archived into Light.legacy.json or something.)

**Comment by scottrick** [comment]
We could create a separate issue for this, but I agree; I think it could be great to have separate json files for the Decipher/Virtual/Legacy cards.

**Comment by thomasmarlin** [comment]
FWIW,  I'd be fine with moving the legacy cards into their own files.  If someone has time to do this, go for it!

**Comment by thomasmarlin** [comment]
> [Light Side] it is!

Agreed!  If someone has time for this, I'll happily approve the PR

**Comment by ronhowe** [comment]
I'll get on it likely tomorrow now that my backlog of PR's have been approved and merged.

**Comment by thomasmarlin** [comment]
Awesome. Thanks Ron.  I very much appreciate your work on this!  Sorry it takes me a while to post back on PRs / issues. I've been trying to limit my technology duties to just a few days per week.
