### ISSUE TITLE
Image Link Updates

### ISSUE THREAD

**Issue by ronhowe** [swccgpc/swccg-card-json#63]
What was the reasoning for these changes?

![image](https://user-images.githubusercontent.com/5210043/109740171-d7c21b80-7b98-11eb-8857-ddb6adc5ade2.png)

Virtual Block image paths didn't change, but the raw=true query string was removed.

Non-Virtual Block image paths changed and the raw=true query string was removed.

I have a parser built that converted these into CDF format.

I can update it to deal with these new edits, but just wanted to make sure they were intentional.

**Comment by thomasmarlin** [comment]
This was a result of the discussion here:
https://github.com/swccgpc/swccg-card-json/issues/49

Initially, Scomp link had a clone of the Holotable images and we hosted them in Amazon with the "Images-HT" prefix.  @DevoKun  created a Github action which automatically sends all of the images up to Amazon S3 now, but without the "Images-HT" prefix. I'm not sure the motivation behind it, but I suspect its to limit the direct dependency on "holotable" image pathing and more to something more agnostic. Perhaps @DevoKun can provide more context.

**Comment by scottrick** [comment]
Also, from what I understand, the `raw=true` was an artifact of the original holotable images and not necessary anymore.

**Comment by ronhowe** [comment]
Sounds good.  I will adjust my parser.
